markdown: rdiscount 
permalink: /:year/:month/:title 
title: 元认知写作通讯
url: http://mesule.com
subscribe: http://mesule.com/feed
exclude: [ README.md, newpost.rb ]
domain: www.mesule.com
author: CnFeat
email: CnFeat@gmail.com
twitterID: feat
duoshuoShortname: cnfeat
safe: true